#!/usr/bin/env node

/**
 * Module dependencies.
 */

var app = require('../app');
var debug = require('debug')('chatcms:server');
var http = require('http');
var fs = require('fs');
var path = require('path');
var https = require('https');

//根据项目的路径导入生成的证书文件
var privateKey  = fs.readFileSync(path.join(__dirname, '../certificate/1751474_www.chenliang.site.key'), 'utf8');
var certificate = fs.readFileSync(path.join(__dirname, '../certificate/1751474_www.chenliang.site.pem'), 'utf8');
var credentials = {key: privateKey, cert: certificate};

var httpsServer = https.createServer(credentials, app);
var SSLPORT = 3002;
//创建https服务器
httpsServer.listen(SSLPORT, function() {
    console.log('HTTPS Server is running on: https://localhost:%s', SSLPORT);
});



/**
 * Get port from environment and store in Express.
 */

var port = normalizePort(process.env.PORT || '3001');
app.set('port', port);

/**
 * Create HTTP server.
 */

var server = http.createServer(app);

var io = require('socket.io')(httpsServer);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}

var sockets = {};

io.on('connect', function(socket){
  console.log("new socket : " + socket.id);
})

io.on('connection',function(socket){
  //监听新成员加入消息
  socket.on('start',function(data){
    var userId = data['userId'];

    sockets[userId] = socket.id;
    io.emit('newUser',{'userId':userId});
  });

  socket.on('singleChat',function(data){
    console.log(data);
    var userId = data['toUserId'];
    io.to(sockets[userId]).emit('singleChat',data);
  });

  socket.on('connect',function(){
     socket.emit("start",{"userId":currentUser});
  });

  socket.on('connect',function(){
     socket.emit("start",{"userId":currentUser});
  });

  socket.on('newMessage',function(data){
    console.log('newMessage:' + data);
    io.emit("newMessage",data);
  });

});